version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - algafood-network

  algafood-api:
    image: algafood-api
 # 24.14: command substitui o comand line do docker file (["java", "-jar", "api.jar"])
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
  # 24.15: remove portas pra poder levantar mais de 1 instancia sem conflitar as portas
  #  ports:
  #   - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
#24.17: novo servico com nginx
  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api